# Generated by Django 4.2.3 on 2023-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source", models.CharField(max_length=200)),
                ("link", models.URLField()),
                ("pub_date", models.DateTimeField()),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
